//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bootstrap_model_data_inserttion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dep_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dep_tbl()
        {
            this.emp_tbl = new HashSet<emp_tbl>();
        }
    
        public int Dep_id { get; set; }
        public string Dep_name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<emp_tbl> emp_tbl { get; set; }
    }
}
