//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bootstrap_model_data_inserttion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class emp_tbl
    {
        public int Emp_id { get; set; }
        public string Emp_name { get; set; }
        public Nullable<int> Dep_id { get; set; }
        public string Address { get; set; }
    
        public virtual Dep_tbl Dep_tbl { get; set; }
    }
}
