//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bootstrap_model_data_inserttion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class site_tbl
    {
        public int site_id { get; set; }
        public Nullable<int> Emp_id { get; set; }
        public string site_name { get; set; }
    }
}
